---
- name: Deploy Database
  hosts: worker2
  vars_files:
    - ../vars/vault_db_credential.yaml
  tasks:
    - name: Deploy Database Server
      become: true
      debug:
        msg:
          "Deploying PostgreSQL database server with the following credentials:
          Username={{ db_username }},
          Password={{ db_password }},
          Host={{ db_host }},
          Port={{ db_port }},
          Database Name={{ db_name }}"
